# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6ac62c5c9107c61a95f390b385ecfe36aa4e4a41df5e4e27e6c5fce0eb11363899d44c641ee646f2c1b1cc14c57f72027b953b5e7b9bf012e320c19cd9e5663

test:
  secret_key_base: 99aab3d577b2a6fa94007c5f9603246fbd540b4ddc90a172c85ef633bd37a6e7d47dbd32d230f896fefba30c4b5d9e3cfbbec6e6682a09190b250df7873e3bc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
